# Required. Username and password that sonarr/radarr use to connect to the proxy
username = "putioarr"
password = "putioarr"

# Required. Directory where the proxy will download files to. This directory has to be readable by
# sonarr/radarr in order to import downloads
download_directory = "/downloads"

# Optional bind address, default "0.0.0.0"
bind_address = "0.0.0.0"

# Optional TCP port, default 9091
port = 9091

# Optional log level, default "info"
loglevel = "info"

# Optional UID, default 1000. Change the owner of the downloaded files to this UID. Requires root.
uid = 1000

# Optional polling interval in secs, default 10.
polling_interval = 10

# Optional skip directories when downloding, default ["sample", "extras"]
skip_directories = ["sample", "extras"]

# Optional number of orchestration workers, default 10. Unless there are many changes coming from
# put.io, you shouldn't have to touch this number. 10 is already overkill.
orchestration_workers = 10

# Optional number of download workers, default 4. This controls how many downloads we run in parallel.
download_workers = 4

[putio]
# Required. Putio API key. You can generate one using `putioarr get-token`
api_key = ""

# Both [sonarr] and [radarr] are optional, but you'll need at least one of them
# [sonarr]
# url = "http://mysonarrhost:8989/sonarr"
# Can be found in Sonarr: Settings -> General
# api_key = "MYSONARRAPIKEY"

# [radarr]
# url = "http://myradarrhost:7878/radarr"
# Can be found in Radarr: Settings -> General
# api_key = "MYRADARRAPIKEY"

# [whisparr]
# url = "http://mywhisparrhost:6969/radarr"
# Can be found in Radarr: Settings -> General
# api_key = "MYWHISPARRAPIKEY"

# [lidarr]
# url = "http://mylidarrhost:6969/lidarr"
# Can be found in Lidarr: Settings -> General
# api_key = "MYLIDARRAPIKEY"
