name: Docker Build and Push

on:
  push:
    branches:
      - main
      - "releases/**"
    tags:
      - v*

env:
  REGISTRY_IMAGE: ghcr.io/wouterdebie/putioarr
  DOCKERFILE_PATH: ./docker/Dockerfile

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@v2
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Determine image tags
        id: docker_tags
        run: |
          TAGS=""
          REF="${{ github.ref }}"
          REF_NAME="${{ github.ref_name }}"
          REGISTRY="${{ env.REGISTRY_IMAGE }}"

          if [[ "$REF" == refs/tags/* ]]; then
            VERSION="$REF_NAME"
            TAGS="$REGISTRY:latest,$REGISTRY:$VERSION"
          elif [[ "$REF" == refs/heads/main ]]; then
            TAGS="$REGISTRY:main-latest"
          elif [[ "$REF" == refs/heads/releases/* ]]; then
            BRANCH_NAME="${{ github.ref_name }}"
            TAGS="$REGISTRY:${BRANCH_NAME}-latest"
          else
            TAGS="$REGISTRY:${{ github.sha }}"
          fi
          echo "TAGS=$TAGS" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.docker_tags.outputs.TAGS }}
